### ISSUE TITLE
Add Newtonsoft.Json requirement to the README

### ISSUE THREAD

**Issue by NaakkaDev** [Rychard/GnomeServer#12]
Hey!

There doesn't seem to no mention about the Newtonsoft.Json framework which the project needs to be installed in the README Installation part. Might want to add that at some point :)

Secondly: Awesome job! It is nice to see that the [Game X]Server idea didn't stop to Cities Skylines.

**Comment by Rychard** [comment]
The `Newtonsoft.Json` package should get picked up automatically upon building the project, since the package is listed in the [`packages.config`](https://github.com/Rychard/GnomeServer/blob/1ebb03a6423aecef8b7b9084785548a2585279be/GnomeServer/packages.config#L4) file.

Or are you referring to something else?

> Secondly: Awesome job! It is nice to see that the [Game X]Server idea didn't stop to Cities Skylines.

Thanks.  It feels great to hear this sort of feedback.

**Comment by NaakkaDev** [comment]
Ah, correct you are. I was not aware that was even possible with VS. All is good, in that regard.
